-- Enum tipovi
CREATE TYPE "StatusMaterijala" AS ENUM ('na čekanju', 'odobreno', 'odbijeno');
CREATE TYPE "NacinPlacanja" AS ENUM ('PayPal', 'Kartica');

-- Tablice
CREATE TABLE "Uloge" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "naziv" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "Korisnici" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ime" varchar(100),
  "email" varchar(100) UNIQUE NOT NULL,
  "idUloge" int NOT NULL,
  "datumKreiranja" timestamp DEFAULT now()
);

CREATE TABLE "Kolegiji" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "naziv" varchar(100) NOT NULL,
  "godina" int,
  "semestar" int,
  "datumKreiranja" timestamp DEFAULT now()
);

CREATE TABLE "Materijali" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "naslov" varchar(200) NOT NULL,
  "opis" text,
  "idKolegija" int NOT NULL,
  "autorId" int NOT NULL,
  "godina" int NOT NULL,
  "dozvolaPreuzimanja" boolean DEFAULT true,
  "putanjaDatoteke" text NOT NULL,
  "status" "StatusMaterijala" DEFAULT 'na čekanju',
  "obrisano" boolean DEFAULT false,
  "datumKreiranja" timestamp DEFAULT now()
);

CREATE TABLE "Ocjene" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idKorisnika" int NOT NULL,
  "idMaterijala" int NOT NULL,
  "vrijednost" int,
  "datumKreiranja" timestamp DEFAULT now()
);

CREATE TABLE "Komentari" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idKorisnika" int NOT NULL,
  "idMaterijala" int NOT NULL,
  "tekst" text NOT NULL,
  "datumKreiranja" timestamp DEFAULT now()
);

CREATE TABLE "Pretplate" (
  "idKorisnika" int NOT NULL,
  "idKolegija" int NOT NULL,
  "datumPretplate" timestamp DEFAULT now(),
  PRIMARY KEY ("idKorisnika", "idKolegija")
);

CREATE TABLE "Donacije" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idDonatora" int NOT NULL,
  "idPrimatelja" int NOT NULL,
  "iznos" numeric(10,2) NOT NULL,
  "nacinPlacanja" "NacinPlacanja" NOT NULL,
  "datumUplate" timestamp DEFAULT now()
);

CREATE TABLE "Poruke" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idPosiljatelj" int NOT NULL,
  "idPrimatelj" int,
  "tekstPoruke" text NOT NULL,
  "datumSlanja" timestamp DEFAULT now()
);

CREATE TABLE "Autentifikacije" (
  "idKorisnika" INT PRIMARY KEY,
  "provider" VARCHAR(50) NOT NULL,
  "externalId" VARCHAR(100) NOT NULL
);

CREATE TABLE "Moderacije" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idModeratora" INT NOT NULL,
  "idMaterijala" INT NOT NULL,
  "status" "StatusMaterijala" NOT NULL,
  "komentar" TEXT,
  "datumModeracije" TIMESTAMP DEFAULT now()
);

CREATE TABLE "Obavijesti" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idKorisnika" INT NOT NULL,
  "idMaterijala" INT NOT NULL,
  "datumSlanja" TIMESTAMP DEFAULT now()
);

-- Indeksi
CREATE UNIQUE INDEX "Ocjene_idKorisnika_idMaterijala_idx" ON "Ocjene" ("idKorisnika", "idMaterijala");
CREATE INDEX "idx_materijali_kolegij" ON "Materijali" ("idKolegija");

-- Strani ključevi
ALTER TABLE "Korisnici" ADD FOREIGN KEY ("idUloge") REFERENCES "Uloge" ("id");
ALTER TABLE "Materijali" ADD FOREIGN KEY ("idKolegija") REFERENCES "Kolegiji" ("id");
ALTER TABLE "Materijali" ADD FOREIGN KEY ("autorId") REFERENCES "Korisnici" ("id");
ALTER TABLE "Ocjene" ADD FOREIGN KEY ("idKorisnika") REFERENCES "Korisnici" ("id");
ALTER TABLE "Ocjene" ADD FOREIGN KEY ("idMaterijala") REFERENCES "Materijali" ("id");
ALTER TABLE "Komentari" ADD FOREIGN KEY ("idKorisnika") REFERENCES "Korisnici" ("id");
ALTER TABLE "Komentari" ADD FOREIGN KEY ("idMaterijala") REFERENCES "Materijali" ("id");
ALTER TABLE "Pretplate" ADD FOREIGN KEY ("idKorisnika") REFERENCES "Korisnici" ("id");
ALTER TABLE "Pretplate" ADD FOREIGN KEY ("idKolegija") REFERENCES "Kolegiji" ("id");
ALTER TABLE "Donacije" ADD FOREIGN KEY ("idDonatora") REFERENCES "Korisnici" ("id");
ALTER TABLE "Donacije" ADD FOREIGN KEY ("idPrimatelja") REFERENCES "Korisnici" ("id");
ALTER TABLE "Poruke" ADD FOREIGN KEY ("idPosiljatelj") REFERENCES "Korisnici" ("id");
ALTER TABLE "Poruke" ADD FOREIGN KEY ("idPrimatelj") REFERENCES "Korisnici" ("id");
ALTER TABLE "Autentifikacije" ADD FOREIGN KEY ("idKorisnika") REFERENCES "Korisnici" ("id");
ALTER TABLE "Moderacije" ADD FOREIGN KEY ("idModeratora") REFERENCES "Korisnici" ("id");
ALTER TABLE "Moderacije" ADD FOREIGN KEY ("idMaterijala") REFERENCES "Materijali" ("id");
ALTER TABLE "Obavijesti" ADD FOREIGN KEY ("idKorisnika") REFERENCES "Korisnici" ("id");
ALTER TABLE "Obavijesti" ADD FOREIGN KEY ("idMaterijala") REFERENCES "Materijali" ("id");
