# Generated by Django 5.2.7 on 2025-11-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='post',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
