# Generated by Django 5.2.8 on 2026-01-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_document_author'),
        ('posts', '0006_document_reviewed_at_document_reviewed_by'),
    ]

    operations = [
    ]
