# Generated by Django 5.2.7 on 2026-01-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_merge_20260116_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
    ]
