# Generated by Django 5.2.8 on 2026-01-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_merge_20260116_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.AddField(
            model_name='document',
            name='allow_download',
            field=models.BooleanField(default=True),
        ),
    ]
