# Generated by Django 5.2.7 on 2026-01-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_document_author_document_allow_download'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
