# Generated by Django 5.2.7 on 2026-01-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_merge_20260116_1131'),
        ('posts', '0009_alter_document_options'),
    ]

    operations = [
    ]
