# Generated by Django 5.2.8 on 2025-12-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_faculty_alter_role_name_user_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(choices=[('Fakultet elektrotehnike i računarstva', 'Fakultet elektrotehnike i računarstva')], max_length=255, unique=True),
        ),
    ]
