# Generated by Django 5.2.7 on 2025-12-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_faculty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='PayPal email for receiving donations. Leave blank to disable tips on your posts.', max_length=254, null=True),
        ),
    ]
