# Generated by Django 5.2.7 on 2026-01-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_faculty_name_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_courses',
            field=models.ManyToManyField(blank=True, help_text="Courses the user is subscribed to. Only courses from user's faculty.", related_name='subscribers', to='users.course'),
        ),
    ]
